---
- name: 'Create regular users & groups in cluster LDAP.'
  include_tasks:
    file: "{{ playbook_dir }}/roles/regular-users/tasks/ldap-regular-users.yml"
  when:
   - use_ldap | default(true, true) | bool
   - create_ldap | default(false, true) | bool
   - inventory_hostname in groups['ldap-server'] | default([])

- name: 'Create local regular users & groups.'
  include_tasks:
    file: "{{ playbook_dir }}/roles/regular-users/tasks/local-regular-users.yml"
  when:
   - not use_ldap | default(true, true) | bool
   - inventory_hostname in groups['cluster'] | default([]) or inventory_hostname in groups['jumphost'] | default([])
...