---

- name: generate grub config
  command: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
  become: true
  notify: reboot
  listen: grub2-mkconfig

- name: reboot the machine in desired kernel
  reboot:
  become: true
  listen: reboot
...
