---
- hosts: slurm-management
  name: Dummy to gather facts
  tasks: []

- name: Install virtual compute nodes
  hosts: compute-vm
  tasks:
  roles:
    - slurm-client

- name: Install user interface
  hosts: user-interface
  tasks:
  roles:
    - slurm-client
...