site_name: "{{ slurm_cluster_name | capitalize }} HPC cluster"
theme:
  name: readthedocs
  highlightjs: false
  hljs_languages:
    - yaml
  collapse_navigation: false
  titles_only: false
site_dir: "/var/www/html/{{ slurm_cluster_name }}/"
extra_css:
    - css/custom.css
nav:
  - Home: 'index.md'
  - About: 
    - 'Cluster': 'cluster.md'
    - 'License': 'license.md'
    - 'Contact': 'contact.md'
  - Requesting Accounts:
    - 'Accounts, security and privacy': 'accounts.md'
    - 'Generate SSH key pair for Windows': 'generate-key-pair-mobaxterm.md'
    - 'Generate SSH key pair for macOS & Linux': 'generate-key-pair-openssh.md'
  - Logins:
    - 'Jumphosts, UIs and sessions': 'logins.md'
    - 'SSH client config for Windows': 'logins-windows.md'
    - 'SSH client config for macOS': 'logins-macos.md'
    - 'SSH client config for Linux': 'logins-linux.md'
    - 'Customize your environment': 'custom-environment.md'
  - Storage:
    - 'Keep - What is stored where on {{ slurm_cluster_name | capitalize }}': 'storage.md'
    - 'Data transfers - How to move data to / from {{ slurm_cluster_name | capitalize }}': 'datatransfers.md'
  - Compute:
    - 'Crunch - How to manage jobs on {{ slurm_cluster_name | capitalize }}': 'analysis.md'
  - Technical Specifications:
    - 'Details on the {{ slurm_cluster_name | capitalize }} HPC environment': 'specifications.md'
{% if 'hyperchicken' in slurm_cluster_name or 'fender' in slurm_cluster_name %}
  - Group Specific Documentation:
    - 'Solve-RD - How to find and work with Solve-RD data': 'solve-rd.md'
{% endif %}
#    - 'Support - FAQs, mailinglists & courses': 'support.md'
