---
- name: 'Show the content of the group_vars/[cluster]/vars.yml lfs_mounts variable for debugging purposes.'
  debug:
    msg: "{{ lfs_mounts }}"

- name: 'Show the content of the group_vars/[cluster]/vars.yml pfs_mounts variable for debugging purposes.'
  debug:
    msg: "pfs: {{ item.pfs }} | source: {{ item.source }} | type: {{ item.type }} | rw_options: {{ item.rw_options }}."
  with_items: "{{ pfs_mounts }}"
  when: inventory_hostname in groups['sys-admin-interface']

- name: 'Mount complete Physical File Systems (PFS-ses) on SAIs.'
  mount:
    path: "/mnt/{{ item.pfs }}"
    src: "{{ item.source }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.rw_options }}"
    state: mounted
  with_items: "{{ pfs_mounts }}"
  when: inventory_hostname in groups['sys-admin-interface']
  become: True

- name: 'Create "home" Logical File System (LFS)  on Physical File Systems (PFSs) mounted on SAIs.'
  file:
    path: "/mnt/{{ item.pfs }}/{{ item.lfs }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ lfs_mounts | selectattr('lfs', 'match', '^home$') | list }}"
  when: inventory_hostname in groups['sys-admin-interface']
  become: True

- name: 'Debug: show mount spec for home.'
  debug:
    msg:
      - "lfs: {{ item.lfs }}"
      - "source: {{ pfs_mounts | selectattr('pfs', 'match', item.pfs) | map(attribute='source') }}/{{ item.lfs }}"
      - "path: /{{ item.lfs }}"
      - "type: {{ pfs_mounts | selectattr('pfs', 'match', item.pfs) | map(attribute='type') }}"
      - "options: {{ pfs_mounts | selectattr('pfs', 'match', item.pfs) | map(attribute='rw_options') }}"
  with_items: "{{ lfs_mounts | selectattr('lfs', 'match', '^home$') | list }}"
  become: True

- meta: end_play


#- name: 'Mount home dirs from shared storage.'
#  mount:
#    path: "/{{ item.lfs }}"
#    src: "{{ item.source }}/{{ item.lfs }}"
#    fstype: "{{ item.type }}"
#    opts: "{{ item.options }}"
#    state: present
#  with_items: "{{ lfs_mounts | selectattr('lfs', 'match', '^home$') | list}}"
#  become: True

- name: 'Debug: show mount spec for complete tmp LFS.'
  debug:
    msg: "lfs: {{ item.lfs }} | source: {{ item.source }} | type: {{ item.type }} | options: {{ item.options }}."
  with_items: "{{ lfs_mounts | selectattr('lfs', 'match', 'tmp[0-9]+$') | list}}"

- name: 'Debug: show mount spec for tmp per group.'
  debug:
    msg:
      - "lfs: {{ item.0.lfs }}"
      - "source: {{ item.0.source | regex_replace('GROUP', item.1) }}"
      - "type: {{ item.0.type }}"
      - "options: {{ item.0.options }}"
  with_subelements:
    - "{{ lfs_mounts | selectattr('lfs', 'match', 'tmp[0-9]+$') | list}}"
    - 'groups'

- name: 'Debug: show mount spec for read-write env for sync on DAIs.'
  debug:
    msg: "lfs: {{ item.lfs }} | source: {{ item.source }} | type: {{ item.type }} | options: {{ item.options }}."
  with_items: "{{ lfs_mounts | selectattr('lfs', 'match', '^.?env[0-9]+') | list}}"
  when: inventory_hostname in groups['deploy-admin-interface']

- name: 'Debug: show mount spec for read-only env.'
  debug:
    msg:
      - "lfs: {{ item.lfs }}"
      - "source: {{ item.source }}"
      - "type: {{ item.type }}"
      - "options: {{ item.options }}"
  with_items:
    - "{{ lfs_mounts | selectattr('lfs', 'match', '^.?env[0-9]+') | list }}"
  when: inventory_hostname in groups['compute-vm'] or inventory_hostname in groups['user-interface'] 

#when: "{{ lfs_mounts | selectattr('lfs', 'match', '^apps$') | list}}"


#- name: Mount tmp per group.
#  debug:
#    msg: "lfs: {{ item[0].lfs }} | source: {{ item[0].source }} | destination: {{ item[0].destination }} | type: {{ item[0].type }} | options: {{ item[0].options }} | group: {{ item[1] }}."
#  with_nested:
#    - "{{ lfs_mounts | selectattr('lfs', 'match', '^tmp[0-9]+$') | list}}"
#    - "{{ lfs_mounts | selectattr('lfs', 'match', '^tmp[0-9]+$') | map(attribute='groups') | list}}"



#- name: Mount tmp per group.
#  debug:
#    msg: "lfs: {{ item.0.lfs }} | source: {{ item.0.source }} | destination: {{ item.0.destination }} | type: {{ item.0.type }} | options: {{ item.0.options }} | group: {{ item.1 }}."
#  with_subelements:
#    - "{{ lfs_mounts | selectattr('lfs', 'match', '^tmp[0-9]+$') | list}}"
#    - 'groups'



...
