---
##############################################################################
# NOTE: Openstack RC file must be sourced to be able to use Openstack API.
##############################################################################

- hosts: localhost
  connection: local
  tasks:

  - name: create a security group for the jumphost.
    os_security_group:
      name: jumphost
      state: present
      description: security group for the jumphost.

  - name: Allow ssh to jumphost.
    os_security_group_rule:
      security_group: jumphost
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0

  - name: create a security group for the slurm controller.
    os_security_group:
      name: slurm-controller
      state: present
      description: security group for machine running slurm.

  - name: create a security group for the login node.
    os_security_group:
      name: login-node
      state: present
      description: security group for the login node.

  - name: Allow ssh from the jumphost
    os_security_group_rule:
      security_group: login-node
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_group: jumphost

  - name: create a security group for all machines of the cluster.
    os_security_group:
      name: cluster
      state: present
      description: security group for all machines of the cluster.

  - name: Allow ping
    os_security_group_rule:
      security_group: cluster
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0

  - name: Allow ssh from login-node.
    os_security_group_rule:
      security_group: cluster
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_group: login-node

  - os_security_group_rule:
      security_group: cluster
      protocol: tcp
      port_range_min: 6817
      port_range_max: 6819
      remote_group: slurm-controller

