---
- hosts: slurm
  name: Dummy to gather facts
  tasks: []

- name: Install virtual compute nodes
  hosts: compute-vm
  become: true
  tasks:
  roles:
     - slurm-client

- name: Install user interface
  hosts: interface
  become: true
  tasks:
  roles:
     - slurm-client
