---
#
# Important: maintain correct handler order.
# Handlers are executed in the order in which they are defined 
# and not in the order in whch they are listed in a "notify: handler_name" statement!
#
- name: Restart nslcd service.
  service:
    name: nslcd
    state: restarted
  become: yes
  listen: restart_nslcd

# OddJob has a dependency on DBus.
- name: Run authconfig update.
  shell: "authconfig --enablemkhomedir --update"
  become: yes
  listen: restart_oddjobd
- name: Restart dbusd and oddjobd services.
  service:
    name: "{{item}}"
    state: restarted
  with_items:
    - dbus
    - oddjobd
  become: yes
  listen: restart_oddjobd

- name: Restart sshd service.
  service:
    name: sshd
    state: restarted
  become: yes
  listen: restart_sshd
...