# Register a machine to our ldap
---
- name: Install yum dependencies
  yum:
    state: latest
    update_cache: yes
    name:
      - openldap-clients
      - nss-pam-ldapd
      - openssh-ldap
  notify:
    - restart_nslcd
    - restart_sshd
  become: true

- name: Deploy nslcd.conf
  template:
    src: nslcd.conf
    dest: /etc/nslcd.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart_nslcd
  become: true

- name: Deploy ldap.conf
  template:
    src: ldap.conf
    dest: /etc/ssh/ldap.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_nslcd
  become: true

- name: Deploy nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_nslcd
  become: true

- name: Redeploy sshd config.
  template:
    src: "{{ playbook_dir }}/roles/sshd/templates/sshd_config"
    dest: /etc/ssh/sshd_config
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart_sshd
  become: true

- name: Deploy custom ssh-ldap-wrapper.
  copy:
    src: ssh-ldap-wrapper
    dest: /usr/libexec/openssh/ssh-ldap-wrapper
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Enable services.
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - nslcd
  notify:
    - restart_nslcd
  become: true

- meta: flush_handlers
...
