# Deploy Slurm control host.
---
- name: Add Slurm group.
  group:
    name: slurm
    gid: "{{ slurm_gid }}"
  become: true

- name: Add Munge group.
  group:
    name: munge
    gid: "{{ munge_gid }}"
  become: true

- name: Add Slurm user.
  user:
    name: slurm
    uid: "{{ slurm_uid }}"
    group: slurm
  become: true

- name: Add Munge user.
  user:
    name: munge
    uid: "{{ munge_uid }}"
    group: munge
  become: true

- name: Install munge.key file.
  copy:
    src: "files/{{ slurm_cluster_name }}_munge.key"
    owner: 'munge'
    group: 'munge'
    mode: '0600'
    dest: '/etc/munge/munge.key'
  become: true

- name: Install Slurm management deamons and their dependencies with yum.
  yum:
    state: latest
    update_cache: yes
    name:
      - MySQL-python
      - lua-posix
      - slurm
      - slurm-slurmctld
      - slurm-slurmdbd
      - slurm-perlapi
  notify:
    - reload_munge
    - reload_slurmdbd
    - reload_slurmctld
  become: true

- name: Make sure the database root user is present and grant privileges.
  mysql_user:
    login_host: 127.0.0.1
    login_user: 'root'
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    name: "{{ slurm_storage_user }}"
    password: "{{ slurm_storage_pass }}"
    host: '%'
    priv: '*.*:ALL'
  no_log: True

- name: Create a database for Slurm accounting.
  mysql_db:
    login_host: 127.0.0.1
    login_user: 'root'
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    name: 'slurm_acct_db'
    state: 'present'
  no_log: True

- name: Create folders for Slurm.
  file:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - name: '/etc/slurm'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - name: '/var/log/slurm'
      owner: 'slurm'
      group: 'root'
      mode: '0750'
    - name: '/var/spool/slurm'
      owner: 'slurm'
      group: 'root'
      mode: '0750'
  become: true

- name: Install Slurm config file.
  template:
    src: 'templates/slurm.conf'
    dest: '/etc/slurm/slurm.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: reload_slurmctld
  become: true

- name: Install Slurm DBD config file.
  template:
    src: 'templates/slurmdbd.conf'
    dest: '/etc/slurm/slurmdbd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: reload_slurmdbd
  become: true

- name: Install Slurm scripts.
  copy:
    src: "files/{{ item }}"
    dest: "/etc/slurm/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - 'job_submit.lua'
  become: true

- name: Make sure slurmdbd and munge services are enabled and started.
  systemd:
    name: "{{item}}"
    state: 'started'
    enabled: 'yes'
  with_items:
    - 'munge.service'
    - 'slurmdbd.service'
  become: true

- name: Copy Slurm DB initialization script to host running slurmdbd.
  template:
    src: 'templates/configure_slurm_accounting_db.bash'
    dest: '/etc/slurm/configure_slurm_accounting_db.bash'
    owner: 'root'
    group: 'root'
    mode: '0700'
  become: true

#
# Flush handlers to make sure Slurm DB is present and connection settings have been updated.
#
- meta: flush_handlers

- name: Execute Slurm DB initialization script on host running slurmdbd.
  shell: |
         /etc/slurm/configure_slurm_accounting_db.bash
  tags:
    - create_database
  register: command_result
  # NOTE: cannot use command_result.rc to check for the exit value of script in failed_when or changed_when
  #       as the sacctmgr commands used in the script may return exit code 1 when trying to create/modify
  #       something that already exists. This results in "Nothing new added." on STDOUT, but no message on STDERR.
  #       In case something is really wrong there will be messags printed to STDERR.
  failed_when: "command_result.stderr != ''"

- name: Make sure slurmctld service is enabled and started now that the cluster DB is present.
  systemd:
    name: 'slurmctld.service'
    state: 'started'
    enabled: 'yes'
  become: true

- name: Make backup dir.
  file:
    path: '/root/slurm/backup'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  tags:
    - backup
  become: true

- name: Create Slurm accounting DB backup now.
  shell: |
         /bin/docker run --network host --rm mariadb \
             mysqldump --all-databases -uroot -p{{ MYSQL_ROOT_PASSWORD }} -h 127.0.0.1 \
               > /root/slurm/backup/slurm.sql
  tags:
    - backup
  no_log: true
  become: true

- name: Deploy cron job to backup the Slurm accounting DB every night. Keep 7 backups.
  cron:
    name: 'Slurm database backup'
    minute: '11'
    hour: '3'
    job: >
      /bin/cp --backup=numbered /root/slurm/backup/slurm.sql /root/slurm/backup/slurm_bak.sql
      && /bin/docker run --network host --rm mariadb
      mysqldump --all-databases -uroot -p{{ MYSQL_ROOT_PASSWORD }} -h 127.0.0.1
      > /root/slurm/backup/slurm.sql
      && /bin/find /root/slurm/backup/slurm_bak.sql.* -mtime 7 -delete
  tags:
    - backup
  no_log: true
  become: true
...
