---
- name: Install EGA Fuse Layer
  yum:
    state: latest
    name:
      - ega-fuse-client
  become: true

- file:
    path: /usr/local/fuse-layer
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Install service files.
  template:
    src: templates/ega-fuse-client.service
    dest: /etc/systemd/system/ega-fuse-client.service
    mode: 644
    owner: root
    group: root
  tags:
      - service-files
  become: true

- name: Install config.ini  files.
  template:
    src: templates/config.ini
    dest: /usr/local/fuse-layer/config.ini
    mode: 644
    owner: root
    group: root
  become: true

- name: install service files
  command: systemctl daemon-reload
  become: true

- name: enable service at boot
  systemd:
    name: fuse-layer
    enabled: yes
  become: true

- name: make sure services are started.
  systemd:
    name: fuse-layer.service
    state: restarted
  tags:
      - start-service
  become: true
