---
- name: Install spacewalk client repo.
  yum:
    name: https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.8-client/epel-7-x86_64/00742644-spacewalk-repo/spacewalk-client-repo-2.8-11.el7.centos.noarch.rpm
    state: present

- name: Install spacewalk client packages.
  yum:
   name:
     - rhn-client-tools
     - rhn-check
     - rhn-setup
     - rhnsd
     - m2crypto
     - yum-rhn-plugin
  notify:
    - restart_rhnsd

- name: Enable spacewalk service.
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - rhnsd.service
  notify:
    - restart_rhnsd

- meta: flush_handlers

- name: Register client at the spacewalk server.
  rhn_register:
   state: present
   activationkey: "{{activation_key}}"
   server_url: "{{spacewalk_server_url}}"
   channels: "{{rhn_channels}}"
  register: result
  until: result is succeeded
  retries: 3
  delay: 3
  ignore_errors: yes
  no_log: True

- name: Disable gpgcheck for spacewalk repo.
  lineinfile:
    path: '/etc/yum/pluginconf.d/rhnplugin.conf'
    regexp: '^gpgcheck = [0-9].*'
    line: 'gpgcheck = 0'

- name: Remove all (non-spacewalk) repo config files from /etc/yum.repos.d/.
  shell: "rm -rf /etc/yum.repos.d/*"
  args:
    warn: false

- name: Clear the yum cache.
  command: "yum clean all"
  args:
    warn: false
  ignore_errors: yes

- name: Upgrade all packages to version specified in spacewalk channel.
  yum:
   name: '*'
   state: latest
...
