---
- name: Install spacewalk client repo.
  yum:
    name: https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.8-client/epel-7-x86_64/00742644-spacewalk-repo/spacewalk-client-repo-2.8-11.el7.centos.noarch.rpm
    state: present

- name: install spacewalk client packages.
  yum:
   name:
     - rhn-client-tools
     - rhn-check
     - rhn-setup
     - rhnsd
     - m2crypto
     - yum-rhn-plugin

- name: restart spacewalk daemon
  systemd:
   name: rhnsd.service
   state: restarted

- name: register at the spacewalk server
  rhn_register:
   state: present
   activationkey: "{{activation_key}}"
   server_url: "{{spacewalk_server_url}}"
   channels: "{{rhn_channels}}"
  register: result
  until: result is succeeded
  retries: 3
  delay: 3
  ignore_errors: yes

- name: Disable gpgcheck
  command: sed -i 's/gpgcheck = 1/gpgcheck = 0/g' /etc/yum/pluginconf.d/rhnplugin.conf
  args:
    warn: false

- name: remove all current repos
  shell: "rm -rf /etc/yum.repos.d/*"
  args:
    warn: false

- name: remove all current repos
  command: "yum clean all"
  args:
    warn: false
  ignore_errors: yes

- name: upgrade all packages
  yum:
   name: '*'
   state: latest
