---

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install "ansible-lint[community,yamllint]"
            ansible-galaxy install -r galaxy-requirements.yml
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export ANSIBLE_ROLES_PATH="${HOME}/.ansible/roles/:${ANSIBLE_ROLES_PATH:-}"
            ansible-lint cluster.yml deploy-os_servers.yml > lint_results 2>&1 || true
            cat lint_results
            errors=$(grep -c '^[0-9]* [A-Z].*' lint_results)
            echo '###############################################'
            printf 'Counted %d ansible-lint errors.\n' ${errors:-0}
            echo '###############################################'
            if (( errors > 1 )); then /bin/false; fi
...