---

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible-lint
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ansible-lint cluster.yml > lint_results 2>&1 || true
            errors=$(grep -c "\:" lint_results)
            if (( errors > 100 )); then /bin/false; fi
            cat lint_results
...