---
- name: Set /etc/hosts
  template:
    src: templates/{{ slurm_cluster_name }}_hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true
  tags: ['etc_hosts']
...