---
- name: Install Python 3 for CentOS 7.
  yum:
    state: latest
    update_cache: yes
    name:
      - python36
      - python36-setuptools
      - python36-pip
  become: true

- name: Install MkDocs and deps using pip on CentOS 7.
  shell: |
         python3 -m pip install mkdocs
  become: true
...