---
- name: Include Slurm vars.
  include_vars:
    file: ../../slurm/defaults/main.yml
    name: slurm

- name: Add Slurm group
  group:
    name: slurm
    gid: "{{ slurm['slurm_gid'] }}"

- name: Add Munge group
  group:
    name: munge
    gid: "{{ slurm['munge_gid'] }}"

- name: Add Slurm user
  user:
    name: slurm
    uid: "{{ slurm['slurm_uid'] }}"
    group: slurm

- name: Add Munge user
  user:
    name: munge
    uid: "{{ slurm['munge_uid'] }}"
    group: munge

- name: Install the Slurm client and NHC
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - slurm
    - slurm-slurmd
    - warewulf-nhc

- name: Create folders for Slurm and NHC
  file:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - name: /etc/slurm
      owner: root
      group: root
      mode: 0755
    - name: /etc/nhc
      owner: root
      group: root
      mode: 0755
    - name: /var/log/slurm
      owner: root
      group: root
      mode: 0750
    - name: /var/spool/slurm
      owner: slurm
      group: root
      mode: 0750
    - name: /var/spool/slurmd
      owner: slurm
      group: root
      mode: 0750

- name: Deploy slurm.conf
  template:
    src: roles/slurm/files/slurm.conf
    dest: /etc/slurm/slurm.conf
    mode: 0644

- name: Configure cgroups
  copy:
    src: roles/slurm/files/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    mode: 0644

- name: Deploy slurm prolog/epilog scripts.
  copy:
    src: roles/slurm/files/{{ item }}
    dest: /etc/slurm/
    mode: 0755
  with_items:
      - slurm.prolog
      - slurm.epilog
      - slurm.taskprolog

- name: Install munge_keyfile
  copy:
    src: ../slurm/files/{{ slurm_cluster_name }}_munge.key
    owner: munge
    group: munge
    mode: 0600
    dest: /etc/munge/munge.key

- name: Deploy nhc.conf
  template:
    src: template/nhc.conf
    dest: /etc/nhc/nhc.conf
    owner: root
    group: root
    mode: 0644

- name: Start slurm and munge services
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - slurmd
    - munge
