---
- name: 'Install figlet.'
  yum:
    state: latest
    update_cache: yes
    name: figlet
  become: true

- name: 'Generate figlet ASCII art.'
  shell: |
         figlet "{{ ansible_hostname }}" > "/etc/{{ ansible_hostname }}.figlet"
  register: figlet
  creates: "/etc/{{ ansible_hostname }}.figlet"
  become: true

- name: 'Create /etc/motd.'
  template:
    src: 'templates/motd'
    dest: '/etc/motd'
    owner: root
    group: root
    mode: '0644'
  when: figlet.changed
  become: true
...