---
- name: Set /etc/hosts
  template:
    src: templates/{{ slurm_cluster_name }}_hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true
  tags: ['etc_hosts']

- name: Set /etc/skel/.bashrc .screenrc
  template:
    src: templates/{{ item }}
    dest: /etc/skel/
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true
  with_items:
    - '.bashrc'
    - '.screenrc'

- name: Set hostname to inventory_hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Install some standard software
  yum:
    state: latest
    update_cache: yes
    name:
      - bzip2
      - curl
      - figlet
      - git
      - git-core
      - lsof
      - nano
      - ncdu
      - ncurses-static
      - readline-static
      - screen
      - tcl-devel
      - telnet
      - tmux
      - tree
      - vim
      - wget
  tags:
    - software
...
