---
- name: Set /etc/hosts
  template:
    src: templates/{{ slurm_cluster_name }}_hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true
  tags: ['etc_hosts']

- name: Set hostname to inventory_hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Install some standard software
  yum:
    state: latest
    update_cache: yes
    name:
      - curl
      - git
      - git-core
      - nano
      - ncdu
      - screen
      - telnet
      - tmux
      - tree
      - vim
      - bzip2
      - ncurses-static
      - readline-static
      - tcl-devel
      - figlet
      - wget
  tags:
    - software
...
