---
- name: Set to boot the desired kernel.
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: "GRUB_DEFAULT={{grub_default | default('0')}}"
  become: true
  notify: grub2-mkconfig

- meta: flush_handlers

- name: install lustre client
  yum:
    name: lustre-client-2.10.8-1.el7.x86_64
    state: present
    update_cache: yes
  become: true

- name: make endpoints to mount datahandling storage on.
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - /mnt/dh1/groups
    - /mnt/dh2/groups

- name: load the lustre kernel module.
  modprobe:
    name: lustre
    state: present

- name: set lustre.conf
  template:
    src: templates/lustre.conf
    dest: /etc/modprobe.d/lustre.conf
    mode: 0644
    owner: root
    group: root
    backup: no

- name: Mount dh1
  mount:
    path: /mnt/dh1/groups
    src: 172.23.57.201@tcp11:172.23.57.202@tcp11:/dh1/groups
    fstype: lustre
    opts: ro,seclabel,lazystatfs
    state: present

- name: Mount dh2
  mount:
    path: /mnt/dh2/groups
    src: 172.23.57.203@tcp12:172.23.57.204@tcp12:/dh2/groups
    fstype: lustre
    opts: rw,seclabel,lazystatfs
    state: present

- name: mount all mountpoints in fstab
  # Mount -a does not change anything if nothing needs changing.
  command: mount -a # noqa 301
  args:
    warn: false
